GameplayResourceDef
{
	id				"ammo_mech_low_caliber_lvl2"
	localization_id "resource_name/ammo_mech_low_caliber"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_low_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_low_caliber_icon_bigger"
	hud_visible 	"never"
	order			"30"
}

GameplayResourceDef
{
	id				"ammo_mech_high_caliber_lvl2"
	localization_id "resource_name/ammo_mech_high_caliber"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_high_caliber_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_high_caliber_icon_bigger"
	hud_visible 	"never"
	order			"31"
}

GameplayResourceDef
{
	id				"ammo_mech_liquid_lvl2"
	localization_id "resource_name/ammo_mech_liquid"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_liquid_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_liquid_icon_bigger"
	hud_visible 	"never"
	order			"32"
}

GameplayResourceDef
{
	id				"ammo_mech_explosive_lvl2"
	localization_id "resource_name/ammo_mech_explosive"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_explosive_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_explosive_icon_bigger"
	hud_visible 	"never"
	order			"33"
}

GameplayResourceDef
{
	id				"ammo_mech_energy_cell_lvl2"
	localization_id "resource_name/ammo_mech_energy"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_energy_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_energy_icon_bigger"	
	hud_visible 	"never"
	order			"34"
}
