GameplayResourceDef
{
	id				"ammo_mech_low_caliber_lvl2"
	localization_id "Low caliber advanced" //"resource_name/ammo_mech_low_caliber_lvl2"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_low_caliber_lvl2_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_low_caliber_lvl2_icon_bigger"
	base_storage	"80"
	hud_visible 	"build_menu"
	order			"30"
}

GameplayResourceDef
{
	id				"ammo_mech_high_caliber_lvl2"
	localization_id "High caliber advanced" //"resource_name/ammo_mech_high_caliber_lvl2"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_high_caliber_lvl2_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_high_caliber_lvl2_icon_bigger"
	base_storage	"30"
	hud_visible 	"build_menu"
	order			"31"
}

GameplayResourceDef
{
	id				"ammo_mech_liquid_lvl2"
	localization_id "Liquid advanced" //"resource_name/ammo_mech_liquid_lvl2"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_liquid_lvl2_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_liquid_lvl2_icon_bigger"
	base_storage	"250"
	hud_visible 	"build_menu"
	order			"32"
}

GameplayResourceDef
{
	id				"ammo_mech_explosive_lvl2"
	localization_id "Explosive advanced" //"resource_name/ammo_mech_explosive_lvl2"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_explosive_lvl2_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_explosive_lvl2_icon_bigger"
	base_storage	"3"
	hud_visible 	"build_menu"
	order			"33"
}

GameplayResourceDef
{
	id				"ammo_mech_energy_cell_lvl2"
	localization_id "Energy cell advanced" //"resource_name/ammo_mech_energy_lvl2"
	bp  			""
	type 			"global"
	specific_type 	"ammo"
	icon			"gui/hud/resource_icons/ammo_mech_energy_lvl2_icon"
	bigger_icon		"gui/hud/resource_icons/ammo_mech_energy_lvl2_icon_bigger"
	base_storage	"20"
	hud_visible 	"build_menu"
	order			"34"
}
