
GameplayResourceDef {
	id				"cobalt_bio"
	localization_id "resource_name/cobalt"
	bp  			"items/loot/resources/shard_cobalt_item"
	type 			"global"	
	icon			"gui/hud/resource_icons/cobalt_bio"
	bigger_icon		"gui/hud/resource_icons/cobalt_bio_bigger"
	hud_visible 	"build_menu"
	order   		"8"
}

GameplayResourceDef {
	id				"palladium_bio"
	localization_id "resource_name/palladium"
	bp  			"items/loot/resources/shard_palladium_item"
	type 			"global"	
	icon			"gui/hud/resource_icons/palladium_bio"
	bigger_icon		"gui/hud/resource_icons/palladium_bio_bigger"
	hud_visible 	"build_menu"
	order   		"8"
}

GameplayResourceDef {
	id				"titanium_bio"
	localization_id "resource_name/titanium"
	bp  			"items/loot/resources/shard_titanium_item"
	type 			"global"	
	icon			"gui/hud/resource_icons/titanium_bio"
	bigger_icon		"gui/hud/resource_icons/titanium_bio_bigger"
	hud_visible 	"build_menu"
	order   		"8"
}

GameplayResourceDef {
	id				"uranium_bio"
	localization_id "resource_name/uranium"
	bp  			"items/loot/resources/shard_uranium_ore_item"
	type 			"global"	
	icon			"gui/hud/resource_icons/uranium_bio"
	bigger_icon		"gui/hud/resource_icons/uranium_bio_bigger"
	hud_visible 	"build_menu"
	order   		"8"
}

