GameplayResourceDef
{
	id					"carbon_deepvein"
	localization_id 	"resource_name/carbon_deepvein"
	bp  				"resources/resource_carbon_deepvein"
	type 				"vein"
	ore					"carbonium"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/carbon_vein"
	bigger_icon			"gui/hud/resource_icons/carbon_vein_bigger"
	
	missing_effect 		"voice_over/announcement/carbonium_depleted"
	hud_visible 		"build_menu"	
	
	terrain_material	"ground/resources/carbonium"
	spawn_type			"single"
}

GameplayResourceDef
{
	id					"iron_deepvein"
	localization_id 	"resource_name/iron_deepvein"
	bp  				"resources/resource_iron_deepvein"
	type 				"vein"
	ore					"steel"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/iron_vein"
	bigger_icon			"gui/hud/resource_icons/iron_vein_bigger"
	order   			"29"
	
	missing_effect 		"voice_over/announcement/steel_depleted"
	hud_visible 		"build_menu"
	
	terrain_material	"ground/resources/ironium"
	spawn_type			"single"
}

GameplayResourceDef
{
	id					"cobalt_deepvein"
	localization_id 	"resource_name/cobalt_deepvein"
	bp  				"resources/resource_cobalt_deepvein"
	type 				"vein"
	ore					"cobalt"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/cobalt"
	bigger_icon			"gui/hud/resource_icons/cobalt_bigger"
	order   			"30"
	
	terrain_material 	"ground/resources/cobalt"
	spawn_type			"single"
}

GameplayResourceDef
{
	id					"palladium_deepvein"
	localization_id 	"resource_name/palladium_deepvein"
	bp  				"resources/resource_palladium_deepvein"
	type 				"vein"
	ore					"palladium"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/palladium_vein"
	bigger_icon			"gui/hud/resource_icons/palladium_vein_bigger"
	order   			"31"

	terrain_material	"ground/resources/palladium"
	spawn_type			"single"
}

GameplayResourceDef
{
	id					"titanium_deepvein"
	localization_id 	"resource_name/titanium_deepvein"
	bp  				"resources/resource_titanium_deepvein"
	type 				"vein"
	ore					"titanium"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/titanium_vein"
	bigger_icon			"gui/hud/resource_icons/titanium_vein_bigger"
	order				"33"

	terrain_material	"ground/resources/titanium"
	spawn_type			"single"
}

GameplayResourceDef
{
	id					"uranium_ore_deepvein"
	localization_id 	"resource_name/uranium_ore_deepvein"
	bp  				"resources/resource_uranium_ore_deepvein"
	type 				"vein"
	ore					"uranium_ore"
	random_rotation 	"1"
	icon				"gui/hud/resource_icons/uranium_vein"
	bigger_icon			"gui/hud/resource_icons/uranium_vein_bigger"
	order   			"32"

	terrain_material	"ground/resources/uranium"
	spawn_type			"single"
}
